feat(createBin): form-data usage
readthedocs-fr/bin-client-discord pull request #28
Opened 2021-03-30 20:41 UTC by Mesteery

To avoid any encoding problems (Lazor's advice),
multipart/form-data is now used.

Moreover, Yarn 2, in view of its rapidity, replaces PNPM !
The jest.config.json file no longer exists
in favor of jest in package.json.

Dependencies have also been updated,
notably eslint-config-prettier which, as of v8.0.0, no longer
requires adding prettier/typescript-eslint in the configuration.

Also, the sourceMap is now included in the production build.
The workflow has been readapted.

Finally, the `format` script has been renamed to `lint-fix`,
to make room for the real format: prettier.
This allows to format files that
ESLint can't cover, even with the Prettier plugin.

2021-04-14 18:07 UTC, Julien00859 requested changes
Trop de changements pour un seul commit, un commit normalement c'est une unité minimale de version. Ici ce n'est pas minimal, c'est un metling-pot.

2021-04-14 18:10 UTC, Mesteery commented
oui, de base c'était un refactor d'où le nom de la branche (et j'en ai profité pour ajouter form-data + quelques petites corrections)

2021-04-16 10:39 UTC, Aakodal requested changes
src/events/message/index.ts
```ts
import { extensions } from "../../misc/extensions";
```
==>
```ts
import { extensions } from "../../misc";
```

2021-04-16 10:39 UTC, Aakodal commented on README.md
> +_We use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) for commits messages._
Ce changement de balise markdown était vraiment nécessaire ? :thinking:

2021-04-16 10:39 UTC, Aakodal commented on src/misc/__tests__/BinError.test.ts
> +import { BinError, errors } from "../BinError";
```suggestion
import { BinError, errors } from "..";
```

2021-04-16 10:40 UTC, Mesteery commented on README.md
> +_We use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) for commits messages._
c'est prettier

2021-04-16 10:50 UTC, Aakodal requested changes
Je peux pas faire de suggestion directement parce que GH est un peu relou, mais dans le README.md, il faut changer les commandes pnpm vers yarn

2021-04-22 15:23 UTC, Julien00859 commented
Hello Mestery, avant tout merci pour le temps que tu as passé sur cette PR, on se rend bien compte que c'est un travail conséquent et nous sommes désolés de devoir intervenir.

On en a discuté avec Aakodal et Antoine, nous sommes arrivés à la conclusion que les changements que tu proposes justifient deux pull-request différentes, deux endroits indépendants où il serait judicieux d'avoir une discussion quant à le faire ou non et comment le faire.

Nous avons donc identifié deux contributions :

* Utilisation de `form-data` plutôt que `x-www-form-urlencoded` pour communiquer avec le backend.
* Changement du package manager (pnpm -> yarn 2) et les changements que cela occasionne (GitHub Actions, mises à jour des règles editorconfig, eslint et prettier).

Chacun de ces changements justifie une discussion ouverte avec l'ensemble des contributeurs. Le 2e changement est d'ailleurs une proposition de changement d'organisation. Nous restons sur une code base relativement petite, je peux donc comprendre que les contributeurs ne ressentent pas le besoin de changer l'organisation actuelle, ce sera à discuter avec eux.

Nous fermons cette pull-request non pas parce que nous rejetons les modifications proposées mais parce qu'elles justifient des discussions indépendantes.

Merci,
Julien, Antoine, Aakodal.

2021-04-22 15:23 UTC, closed without merging